# Deliberate faults for tools/mutate.py: (name, exact snippet in the contract, replacement).
# Each must be caught by at least one test.
MUTATIONS = [
    ("praise does not debit the writer's allowance",
     "            self.allowance[caller] = u256(self._balance_of(self.allowance, caller) - tip)\n",
     ""),
    ("praise does not credit the creator",
     "            self.earnings[creator] = u256(self._balance_of(self.earnings, creator) + tip)\n",
     ""),
    ("NOT_PRAISE also moves the tip",
     "        if outcome == SINCERE_PRAISE:\n            moved = tip",
     "        if True:\n            moved = tip"),
    ("praised_count not incremented",
     "            record.praised_count = u256(int(record.praised_count) + 1)\n",
     ""),
    ("tip credited to the writer instead of the creator",
     "            self.earnings[creator] = u256(self._balance_of(self.earnings, creator) + tip)",
     "            self.earnings[caller] = u256(self._balance_of(self.earnings, caller) + tip)"),
    ("allowance check off by one (allowance must exceed the tip)",
     "        if self._balance_of(self.allowance, caller) < tip:",
     "        if self._balance_of(self.allowance, caller) <= tip:"),
    ("allowance checked after the model call",
     "        tip = int(record.tip_wei)\n        if self._balance_of(self.allowance, caller) < tip:\n            raise gl.vm.UserError(\"Fund your allowance before replying\")\n\n        outcome = self._judge(record.title, clean)\n",
     "        tip = int(record.tip_wei)\n        outcome = self._judge(record.title, clean)\n        if self._balance_of(self.allowance, caller) < tip:\n            raise gl.vm.UserError(\"Fund your allowance before replying\")\n"),
    ("fail-safe flipped on unparseable output",
     "                    return {\"outcome\": NOT_PRAISE}\n            if not isinstance(data, dict):",
     "                    return {\"outcome\": SINCERE_PRAISE}\n            if not isinstance(data, dict):"),
    ("unknown label maps to SINCERE_PRAISE",
     "            if outcome == SINCERE_PRAISE:\n                return {\"outcome\": SINCERE_PRAISE}\n            return {\"outcome\": NOT_PRAISE}",
     "            if outcome == NOT_PRAISE:\n                return {\"outcome\": NOT_PRAISE}\n            return {\"outcome\": SINCERE_PRAISE}"),
    ("validator accepts any valid label",
     "                return str(mine.get(\"outcome\", \"\")).strip().upper() == leader_outcome",
     "                return True"),
    ("creator may reply to their own jar",
     "        if caller == creator:\n            raise gl.vm.UserError(\"The creator cannot reply to their own jar\")",
     "        if caller == \"\":\n            raise gl.vm.UserError(\"The creator cannot reply to their own jar\")"),
    ("second reply per wallet allowed",
     "        if by_key in self.reply_by:", "        if by_key in self.reply_by and False:"),
    ("reply_by not recorded",
     "        self.reply_by[by_key] = str(index)\n", ""),
    ("anyone may close a jar",
     "        if caller != str(record.creator).lower():", "        if caller == \"\":"),
    ("withdraw_allowance does not debit before the transfer",
     "        self.allowance[caller] = u256(available - amount)\n", ""),
    ("withdraw_allowance allows more than the allowance",
     "        if amount <= 0 or amount > available:", "        if amount <= 0:"),
    ("withdraw_earnings does not zero before the transfer",
     "        self.earnings[caller] = u256(0)\n", ""),
    ("zero-value funding accepted",
     "        if value <= 0:", "        if value < 0:"),
    ("tip minimum off by one",
     "        if tip_wei < MIN_TIP_WEI or tip_wei > MAX_TIP_WEI:",
     "        if tip_wei <= MIN_TIP_WEI or tip_wei > MAX_TIP_WEI:"),
    ("tip maximum off by one",
     "        if tip_wei < MIN_TIP_WEI or tip_wei > MAX_TIP_WEI:",
     "        if tip_wei < MIN_TIP_WEI or tip_wei >= MAX_TIP_WEI:"),
    ("title length cap off by one",
     "        if len(clean) > MAX_TITLE_LENGTH:", "        if len(clean) >= MAX_TITLE_LENGTH:"),
    ("reply length cap off by one",
     "        if len(clean) > MAX_COMMENT_LENGTH:", "        if len(clean) >= MAX_COMMENT_LENGTH:"),
    ("reserved token not checked on replies",
     "            raise gl.vm.UserError(\"Reply is too long\")\n        if self._contains_reserved_token(clean):",
     "            raise gl.vm.UserError(\"Reply is too long\")\n        if False:"),
    ("fence strip: no gap and a single pass (cross-token rebuild survives)",
     "            cleaned = cleaned[:index] + \" \" + cleaned[index + len(token):]\n\n    def _fence_strip(self, value: str) -> str:\n        # Fixed point: repeat until nothing changes, so nested fragments\n        # such as \"<<TAG>TAG>\" cannot rebuild a marker after one pass.\n        cleaned = value\n        while True:\n            before = cleaned\n            for token in RESERVED_TOKENS:\n                cleaned = self._remove_token(cleaned, token)\n            if cleaned == before:\n                return \" \".join(cleaned.split())",
     "            cleaned = cleaned[:index] + cleaned[index + len(token):]\n\n    def _fence_strip(self, value: str) -> str:\n        cleaned = value\n        for token in RESERVED_TOKENS:\n            cleaned = self._remove_token(cleaned, token)\n        return \" \".join(cleaned.split())"),
    ("wallet leaks into the prompt",
     "        safe_reply = self._fence_strip(reply_text)",
     "        safe_reply = self._fence_strip(reply_text) + \" \" + str(gl.message.sender_address)"),
    ("tip amount leaks into the prompt",
     "        outcome = self._judge(record.title, clean)",
     "        outcome = self._judge(record.title, clean + \" \" + str(tip))"),
    ("state checked after caller",
     "        if record.state != JAR_OPEN:\n            raise gl.vm.UserError(\"This jar is closed\")\n        caller = str(gl.message.sender_address).lower()\n        creator = str(record.creator).lower()\n        if caller == creator:",
     "        caller = str(gl.message.sender_address).lower()\n        creator = str(record.creator).lower()\n        if caller == creator:\n            raise gl.vm.UserError(\"The creator cannot reply to their own jar\")\n        if record.state != JAR_OPEN:\n            raise gl.vm.UserError(\"This jar is closed\")\n        if caller == creator:"),
    ("jar id ignores whitespace normalization",
     "        jid = self._jar_id(str(sender).lower(), self._normalize_text(clean))",
     "        jid = self._jar_id(str(sender).lower(), clean)"),
]
